### ISSUE TITLE
主菜单界面设计

### ISSUE THREAD

**Issue by Chengjie-Huang** [Chengjie-Huang/Android-2021#11]
### 效果显示
![截屏2021-11-05 00 48 46](https://user-images.githubusercontent.com/93354345/140440006-d526820a-9d58-4de6-8481-8541fcb2602b.png)

### 说明
1. 左边按钮用来自定位
2. 右下按钮是主菜单按钮
3. 右下按钮上边两个按钮后续我会先设置成invisible, 然后按了主菜单按钮后才变成visible, 或者得按了主菜单按钮后再生成这两个按钮的view. 现在由于没有写kotlin代码, 先设置成这样
4. 底部的照片预览栏也是得有kotlin代码才好加, 之后再加

**Comment by GJD98** [comment]
没问题，通过

**Comment by DHT99** [comment]
通过

**Comment by Chengjie-Huang** [comment]
两个通过, close
