### ISSUE TITLE
visit界面效果

### ISSUE THREAD

**Issue by GJD98** [Chengjie-Huang/Android-2021#12]
<img width="269" alt="截屏2021-11-05 16 21 02" src="https://user-images.githubusercontent.com/93408491/140544494-68376142-b866-4558-bd77-e748b297fff2.png">
<img width="295" alt="截屏2021-11-05 16 21 50" src="https://user-images.githubusercontent.com/93408491/140544284-e5212d77-7d19-4e83-8f07-0b131cf4180b.png">
说明
visit基本界面；
visit2界面地图后期添加；

**Comment by Chengjie-Huang** [comment]
第一张图的Title可以去掉, 没有明白存在的意义是什么. New Visit底色太丑. 
框架上其余的倒是还行. 不过美化还是存在很大的空间. 后续还是得在界面上做改进.
可以先改掉我说的两点, 当然如有异议请直接评论回复.

**Comment by GJD98** [comment]
> 第一张图的Title可以去掉, 没有明白存在的意义是什么. New Visit底色太丑. 框架上其余的倒是还行. 不过美化还是存在很大的空间. 后续还是得在界面上做改进. 可以先改掉我说的两点, 当然如有异议请直接评论回复.

收到

**Comment by DHT99** [comment]
日期框和时间框如果能统一格式会更简洁，其余通过。
