### ISSUE TITLE
搜索界面、细节界面实现

### ISSUE THREAD

**Issue by DHT99** [Chengjie-Huang/Android-2021#13]
![search](https://user-images.githubusercontent.com/91605783/140613404-785240b2-6542-4fa8-b66d-19be13a923fd.png)
![detail](https://user-images.githubusercontent.com/91605783/140613414-773c5e44-6d64-4401-8480-69c6790f5fb2.png)
1.搜索界面添加了标题和图片来填补空白，删除了描述行。
2.细节界面临时改变了文字颜色，突出了层次感。后期可根据UI开发过程更改合适颜色。
3.细节界面增加了change按钮，以准备未来实现更改细节功能。

**Comment by Chengjie-Huang** [comment]
这两个界面基础框架可以, 还是得留意后期美工进一步优化.
同样的search界面的title框可以去掉, 属于设计冗余.
遗漏了一个search后跳转到图片的界面, 要备注一下.
其余的阶段性ok.

**Comment by DHT99** [comment]
跳转界面是还要一个界面？
