### ISSUE TITLE
搜索界面、细节界面实现（改）

### ISSUE THREAD

**Issue by DHT99** [Chengjie-Huang/Android-2021#14]
![detail](https://user-images.githubusercontent.com/91605783/140614308-8f7f2201-1c44-4547-8f92-944168cd5f12.png)
![photo](https://user-images.githubusercontent.com/91605783/140614314-4b1fbf33-1512-4107-a8a5-3285b23a3e25.png)
![search(改)](https://user-images.githubusercontent.com/91605783/140614319-3d9ad616-3971-49ae-b909-94346fe48a71.png)
1.删除了搜索界面标题
2.增加了相册界面

**Comment by Chengjie-Huang** [comment]
界面设置ok
我之后看代码

**Comment by GJD98** [comment]
没问题，之后把咱们界面的一些组件统一一下大小规格，比如按键输入框什么的
