### ISSUE TITLE
按钮双击产生bug

### ISSUE THREAD

**Issue by GJD98** [Chengjie-Huang/Android-2021#23]
**问题点**
首页右下角按钮双击后位置错误
**问题代码截图**
...
**问题编译或者运行报错截图**
**app显示截图**
![image](https://user-images.githubusercontent.com/93408491/141333906-50e7ea57-6c8e-4c87-bfd2-7a7f6cf088e8.png)
![image](https://user-images.githubusercontent.com/93408491/141334103-9caf0050-0e51-4995-839b-4633b0019ba0.png)

**Comment by Chengjie-Huang** [comment]
已解决
